#!/usr/bin/env python3
# Copyright 2026 Multiscale Modeling of Fluid Materials, TU Munich
# SPDX-License-Identifier: Apache-2.0
"""Export CPU regression fixtures and start the standalone Bazel test.

This launcher is the supported entrypoint for the full CPU connector
regression. It has no LAMMPS, MPI, Kokkos, or GPU dependency. The bundle path
is passed explicitly so the C++ test only depends on the public JCN C API.
"""

from __future__ import annotations

import argparse
import os
from pathlib import Path
import subprocess
import sys


def main() -> None:
    """Export bundles, then invoke the CPU-only public-API regression target."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output-directory",
        type=Path,
        default=Path.cwd() / "cpu-regression-models",
        help="directory receiving generated .ptb fixtures",
    )
    parser.add_argument(
        "--bazel",
        default="bazel",
        help="Bazel executable or the repository-pinned Bazel launcher",
    )
    parser.add_argument(
        "--bazelrc",
        type=Path,
        help="Bazel configuration generated by chemtrain-deploy/build.py",
    )
    parser.add_argument(
        "--output-base",
        type=Path,
        help="reuse the connector build's Bazel output base",
    )
    args, remaining = parser.parse_known_args()

    regression_directory = Path(__file__).resolve().parent
    workspace = regression_directory.parent

    # Export the source-controlled model definitions into temporary bundles.
    subprocess.run(
        [
            sys.executable,
            str(regression_directory / "export_cpu_models.py"),
            str(args.output_directory),
        ],
        cwd=workspace,
        check=True,
    )

    # Run the adapter-level regression against the installed connector.
    environment = os.environ | {
        "JCN_CPU_REGRESSION_MODEL_DIR": str(args.output_directory.resolve()),
    }
    pjrt_path = environment.get("JCN_PJRT_PATH")
    if not pjrt_path:
        raise RuntimeError(
            "JCN_PJRT_PATH must identify the installed pjrt directory"
        )

    if remaining[:1] == ["--"]:
        remaining = remaining[1:]
    bazel_startup_options = []
    if args.bazelrc is not None:
        bazel_startup_options.append(f"--bazelrc={args.bazelrc.resolve()}")
    if args.output_base is not None:
        bazel_startup_options.append(
            f"--output_base={args.output_base.resolve()}"
        )
    subprocess.run(
        [
            args.bazel,
            *bazel_startup_options,
            "test",
            "//regression:cpu_connector_regression_test",
            "--cache_test_results=no",
            "--test_env=JCN_CPU_REGRESSION_MODEL_DIR="
            f"{args.output_directory.resolve()}",
            f"--test_env=JCN_PJRT_PATH={Path(pjrt_path).resolve()}",
            *remaining,
        ],
        cwd=workspace,
        env=environment,
        check=True,
    )


if __name__ == "__main__":
    main()
