# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: model.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'model.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bmodel.proto\x12\x03jcn\"\x83\x03\n\x05Model\x12\x13\n\x0bmlir_module\x18\x01 \x01(\t\x12.\n\rneighbor_list\x18\x04 \x01(\x0b\x32\x17.jcn.Model.NeighborList\x12\x17\n\nunit_style\x18\x05 \x01(\tH\x00\x88\x01\x01\x12\x12\n\nquantities\x18\x06 \x03(\t\x1a\x9b\x01\n\x0cNeighborList\x12)\n\x04type\x18\x01 \x01(\x0e\x32\x1b.jcn.Model.NeighborListType\x12\x0e\n\x06\x63utoff\x18\x02 \x01(\x02\x12\x11\n\tnbr_order\x18\x03 \x03(\x05\x12\x16\n\thalf_list\x18\x04 \x01(\x08H\x00\x88\x01\x01\x12\x17\n\x0fstatistics_keys\x18\x05 \x03(\tB\x0c\n\n_half_list\"[\n\x10NeighborListType\x12\x0f\n\x0bUNSPECIFIED\x10\x00\x12\x11\n\rDEVICE_SPARSE\x10\x01\x12\x10\n\x0cSIMPLE_DENSE\x10\x02\x12\x11\n\rSIMPLE_SPARSE\x10\x03\x42\r\n\x0b_unit_styleb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'model_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MODEL']._serialized_start=21
  _globals['_MODEL']._serialized_end=408
  _globals['_MODEL_NEIGHBORLIST']._serialized_start=145
  _globals['_MODEL_NEIGHBORLIST']._serialized_end=300
  _globals['_MODEL_NEIGHBORLISTTYPE']._serialized_start=302
  _globals['_MODEL_NEIGHBORLISTTYPE']._serialized_end=393
# @@protoc_insertion_point(module_scope)
