name: PushGitlab

on:
  push:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.2
      with: 
        fetch-depth: 0
        lfs: true
    - name: Checkout LFS
      run: git lfs pull
    - name: Push To Gitlab
      env: 
        token: ${{ secrets.GITLAB_TOKEN }}
      run: |
        echo Starting to push repo to gitlab
        git config user.name "tummfm"
        git config user.email "tummfm@noreply.github.com"
        git lfs install
        git remote set-url origin "https://oauth2:${token}@gitlab.lrz.de/mfm/science/chemtrain.git"
        git push origin main
